void main() 
{

   TRISC=0x00;     //PUERO C COMO SALIDA  - MOSTRARA EL ADRESL
   TRISD.RD0=0;    // BIT 0 DEL PUERTO C COMO SALIDA - MOSTRARAN EL ADRESH
   TRISD.RD1=0;    // BIT 1 DEL PUERTO C COMO SALIDA
   
   TRISA.RA3=1;    //BIT 0 DEL PUERTO A COMO ENTRADA
   ANSEL.RA3=1;    //BIT 0 DEL PUERTCO A COMO ENTRADA ANÁLOGA
   
   ADCON0.ADCS1=1;  //SELECCIÓN DEL OSCILADOR
   ADCON0.ADCS0=1;  //SELECCIÓN DEL CANAL 0 DE FORMA PREDETERMINADA
   
   ADCON1.ADFM=1;      //JUSTIFICACION A LA DERECHA
                       //SELECICION PREDEFINADA DEL Vref(VDD A VSS)
   ADCON0.ADON=1;      //ENCENCIDO DEL ADC
   
   while(1)
   {
    delay_ms(100);     //TIEMPO DEL MUESTREO
    ADCON0.GO_DONE=1;  //INICIO DE CONVERSIÓN
    
    while(ADCON0.GO_DONE)
    {
                     // ESPERA DE LA CONVERSIÓN "PELEO"
    }
    PORTC=ADRESL;   //MUESTRA LOS 10 BITS DE CONVERSIÓN.
    PORTD=ADRESH;
   }

}